spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: resources/schema.sql

bootstrap:
  database:
    enabled: true
    names-path: data/canonical/baby_names.parquet